In [56]:
import numpy as np

In [57]:
two_array = np.random.randint(1,21,(3,3))

In [58]:
two_array

array([[14, 10, 15],
       [16, 20,  9],
       [ 2, 16,  1]])

In [59]:
two_array.shape

(3, 3)

In [60]:
two_array.size

9

In [61]:
two_array.dtype

dtype('int32')

In [64]:
two_array[0,:]

array([14, 10, 15])

In [65]:
two_array[:,-1]

array([15,  9,  1])

In [66]:
store_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [67]:
store_2d.sum()

45

In [68]:
np.sum(store_2d, axis=1)

array([ 6, 15, 24])

In [69]:
np.sum(store_2d, axis=0)

array([12, 15, 18])

In [70]:
one_d_array = np.arange(10, 31, 4)
two_d_array = one_d_array.reshape(2, 3)
div_by_five = two_d_array[two_d_array % 5 ==0]

In [71]:
div_by_five

array([10, 30])